### ISSUE TITLE
Getting SQL Error SQLSTATE[08006] [7]  on CSV Device Query

### ISSUE THREAD

**Issue by rogeralthaus** [ttnmapper/ttnmapper-website#1] opened 2022-08-05 16:43 UTC
Error: SQLSTATE[08006] [7] could not translate host name "port=0" to address: Name or service not knownAn error occured running the query.

On the 22.07.2022 the CSV Export was working successful.

[Query-Url](https://ttnmapper.org/devices/csv-pg.php?device=eui-3535313156376307&startdate=&enddate=&gateways=on&lines=on&points=on)

**Comment by jpmeijers** [comment] 2022-08-10 07:25
Thanks for reporting. The issue is also followed here: https://github.com/ttnmapper/bugtracker/issues/18

**Comment by jpmeijers** [comment] 2022-08-14 10:14
Fixed by https://github.com/ttnmapper/ttnmapper-website/commit/f228365268e451b256652f67dbc3720236b3069b

**Closed as completed by jpmeijers** 2022-08-14 10:14 UTC
